--- 
# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NovaStark1234/SellStick
build-by-default: true
branches:
- main
projects:
  SellStick:
    path: ""
    icon: "icon.png"
    libs:
    - src: YTBJero/LibEconomy/Economy
      version: ^1.0.0-alpha
    lint:
      phpstan: true
...
